name: "CI"
on: "push"
jobs:
  lint:
    name: "🐍 Test Python modules"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
        dependencies: ["", "colorama"]
    steps:
      - uses: "actions/checkout@master"
      - name: "🐍 Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "🐍 Display Python version"
        run: "python --version"
      - name: "🐍 Install dependencies"
        run: "python -m pip install --user flake8 pytest ${{ matrix.dependencies }}"
      - name: "🐍 Run flake8"
        run: "python -m flake8"
      - name: "🐍 Run pytest"
        run: "python -m pytest"
  publish:
    name: "📦 Publish Python distributions"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: "actions/checkout@master"
      - name: "🐍 Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "🐍 Display Python version"
        run: "python --version"
      - name: "🐍 Install wheel"
        run: "python -m pip install wheel --user"
      - name: "🐍 Build a binary wheel and a source tarball"
        run: "python setup.py sdist bdist_wheel"
      - name: "📦 Publish distribution to PyPI"
        uses: "pypa/gh-action-pypi-publish@master"
        if: "startsWith(github.ref, 'refs/tags')"
        with:
          password: "${{ secrets.pypi_password }}"
